### ISSUE TITLE
ToDo: followsups / extras / ideas [cont.... yet again]

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [hardenFF/tzp#66]
previous: #28, #46, #54 

---

### 🔹 Pages I use to keep tabs on a few things

- [SpiderMonkey changes](https://mozilla-spidermonkey.github.io/blog/)
- [L10N](https://blog.mozilla.org/l10n/)
- [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) (not always up to date!)

---

### :small_red_triangle_down: ToDo

:small_blue_diamond: screen
* [ ] screen: update/add border-snapping subPixel devicePixelRatio PoC to use domrect
* [ ] screen: improve android keyboard PoC to use setInterval to detect a static change
* [ ] screen: android 73+: see [1514429](https://bugzilla.mozilla.org/1514429):
* [ ] screen: android: investigate a history of changes as soon as possible
   - e.g global.js is where I grab initial viewport and window sizes
* [ ] screen: android: exploit `font inflation`
* [ ] screen: android: exploit position (top/bottom) of toolbar in Fenix [yes, I can detect this]

:small_blue_diamond: ua
* [ ] ua: worker/iframe nav checks
   * add nested worker & worker from blob & all iframe tests
   * make all tests handle failures and  promise/resolve into a single array: output unique leaks
   * combine/split duplicate/diff hashes per type: workers / iframes
* [ ] ua: finish UA BS detection
   - this is implausible results based on feature detection and typos/spaces etc and accounts for RFP

:small_blue_diamond: math
* [ ] math: research (and use) new test for FF78+, see #78 (how appropriate is that issue number! 😀 )

:small_blue_diamond: language
* [ ] language: investigate `getCanonicalLocales`
* [ ] language: add `Intl.Segmenter` [1423593](https://bugzilla.mozilla.org/show_bug.cgi?id=1423593), [spec](https://tc39.es/proposal-intl-segmenter/)
* [ ] language: add/investigate `Temporal` API [spec](https://tc39.es/proposal-temporal/docs/index.html)

:small_blue_diamond: storage
* [ ] storage: finish the tests

:small_blue_diamond: devices
* [ ] devices: finish pointer tests
* [ ] devices: android: touch tests: `radiusX/Y`, `screenX/Y`, `clientX/Y`
* [ ] devices: enumerate gamepads
* [ ] devices: enumerate vrdisplays
* [ ] devices: use precision timing bypasses to estimate cores

:small_blue_diamond: domrect / SVG
* [ ] domrect: check **every** method: BBox, rootBounds etc .. see #67 
* [ ] domrect: expand to include a SVG subsection
   - ExtentOfChar
   - SVGTextContentElement.prototype.getComputedTextLength
   - SVGPathElement.prototype.getTotalLength
   - SVGGeometryElement.getPointAtLength()
* [ ] domrect: overall hash per subsection

:small_blue_diamond: canvas
* [ ] canvas: add offscreenCanvas
* [ ] canvas: add iframe tests
* [ ] canvas: add `noise` fingerprint... maybe
* [ ] canvas: get size? get number of colors? see #60 
* [ ] canvas: decide if stability is important see #60 
   - the canvas content is causing changes between some FF releases whereas CB's doesn't (but did on Nightly)

:small_blue_diamond: webgl
* [ ] webgl: readPixels: expand/test on error entropy
   - e.g. in VM's which usually block the graphics driver and the error messages can differ
   - make sure error entropy is handled for TB slider and VMs
* [ ] webgl: build it: image1+image2, parameters, colors, size, iframe tests

:small_blue_diamond: audio
* [ ] audio: expand tests, see #58 (sine + triangle, delayed, hrtz)
* [ ] audio: error trapping and no silent failures
* [ ] audio: are we checking all methods/APIs ?
* audio: FF78+ audioLatency (and RFP off) seems to return zero even on the second attempt
   - a decent wait for a second try fixes it: e.g. 1000ms
   - update: this seems to be fixed: leaving here to remind me to keep checking it

:small_blue_diamond: fonts
* [ ] fonts: textMetrics: randomness
   - fixup: double char non-matching
   - exploit number of decimal places
   - apply to getBounding
* [ ] fonts: fontfallback: investigate further
   - when document fonts are blocked, the first run misses fonts it picks up on subsequent tests: currently mitigated by doing a 2-font "priming" run: but this is not an elegant solution
* [ ] fonts: list improvements - see #43
* [ ] fonts: graphite
* [ ] fonts: default font-family name: serif + san-serif
* [ ] fonts: font versions: Times New Roman, Arial [thru unicode changes per version]

:small_blue_diamond: media
* [ ] media: improve audio/video lists
   - reduce list for perf (we only care about FF)
   - add items for entropy
* [ ] media: image hash: encoding/decoding FP?
* [ ] media: mediacapabilities FP

:small_blue_diamond: css
* [ ] css: prefers-contrast notation - [tests](https://bugzilla.mozilla.org/show_bug.cgi?id=1651857), [article](https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/)
    - WTF is this [1658780](https://bugzilla.mozilla.org/show_bug.cgi?id=1658780)
* [ ] css: prefers-forced-colors notation

:small_blue_diamond: misc

:small_blue_diamond: other
* [ ] other: "interference" detection (i.e extension function names etc)
* [ ] other: ongoing ... robust error handling, detection of script blockage
* [ ] other: WebRTC
* [ ] other: isAdBlocking [also: hash of results]
* [ ] other: sanitizing / zombie storage - [prototype](https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html)
* [ ] other: widgets/form controls
* [ ] other: RFP timing tests - [temp demo / ideas](https://thorin-oakenpants.github.io/testing/timing.html)
* [ ] other: elements (and injecting resource:// css files for app lang leaks)
* [ ] other: AOM (accessability object model)

:small_blue_diamond: randomizing detection
* [ ] random: audio / ~~domrect~~ / ~~measureText~~ (see textMetrics) / ~~canvas~~ (see canvas noise)
* [ ] random: ^^ might be useful for css line-height / unicode gylphs 

---

### Done :small_red_triangle_down:

July-2020
* [x] ua: v80 detection
* [x] canvas: add `noise` detection: i.e detect stealth as compared to random on each pass
   - all done: added isPointInPath and isPointInStroke
* [x] css: computedStyles, see #68 

August-2020
* [x] misc: iframe properties
   - misc: window properties not needed, see #68 
* [x] ua: v81 test
* [x] css: computedStyles expanded, thanks to @abrahamjuliot 💋 🍻 
   - getComputedStyle, HTMLElement.style, CSSRuleList.style
* [x] css: prefers-forced-colors
* [x] language: formatRange added [1496584](https://bugzilla.mozilla.org/1496584), [1653024](https://bugzilla.mozilla.org/1653024), [spec](https://github.com/tc39/proposal-intl-DateTimeFormat-formatRange)
* [x] language: timezone expanded to four dates to cover more DST
* [x] language: expanded **locale** resolved options, thanks to @abrahamjuliot  👍 
   - Collator, DisplayNames, NumberFormat, RelativeTimeFormat
* [x] language: display: merged 3 x navigator and 7 x locale resolvedOptions into two lines
* [x] language: timezone values
   - order is now ascending Jan-Apr-Jul-Oct and all use the current year
   - day is now mid month instead of the 30th: I don't think it really matters, TBH, `¯\_(ツ)_/¯` but since I use 1300hrs, this will stop some TZ's tipping into the next month
* [x] language: PluralRules added
* [x] ua: version: v81 faster test
* [x] ua: version: if a version test has fallback test(s), then the fallback test number is output if it is used
   - e.g. 81 test = `File API` if blocked -> `a css layout test`
   - e.g. 78 test = `ListFormat` if blocked -> `NumberFormat` if blocked -> `regex.dotAll`

..

**Comment by Thorin-Oakenpants** [comment]
@sereneblue 

today:
* [x] language: expanded locale resolved options, thanks to @abrahamjuliot 👍
   - Collator, DisplayNames, NumberFormat, RelativeTimeFormat

DisplayNames hasn't [shipped](https://bugzilla.mozilla.org/show_bug.cgi?id=1654116) in FF yet, but the other three **resolved options** aren't covered by Chamelon

![locales](https://user-images.githubusercontent.com/16656956/90763424-351a0d80-e2d6-11ea-8af4-9af81455d379.png)
